version: '3.5'
services:
  api1:
    build:
      context: .
    hostname: api1
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:rinhabackend2023q3@db/rinhabackend2023q3
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    build:
      context: .
    hostname: api2
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:rinhabackend2023q3@db/rinhabackend2023q3
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rinhabackend2023q3
      MYSQL_DATABASE: rinhabackend2023q3
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
